version: "3.3"
services:
    api:
  
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment: 
            DATABASE_URL: postgres://postgres:Ahmed@123@postgres:5432/db
            NODE_ENV: development
            PORT: 5000
        ports:
            - "8000:5000"

    postgres:
        image: postgres:10.4
        ports:
            - "27000:5432"
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: Ahmed@123
            POSTGRES_DB: db    

